### ISSUE TITLE
Exit code -1073740791 when I run my app on IIS 10

### ISSUE THREAD

**Issue by scharez** [smartinmedia/Net-Core-DocX-HTML-To-PDF-Converter#19]
Hi,

can anyone help regarding this bug. It seems the converter is accessing LibreOffice, but I get -1073740791 exit code.

thank you.

**Comment by cturner-pulsion** [comment]
After running into the same issue, I was able to recreate locally which gave a more descriptive error message

> System.UnauthorizedAccessException: Access to the path '(redacted)\wwwroot\pdfDocument_temp.html' is denied.

Running libre office from the command line as a non admin user also resulted in no file being generated

`./soffice --headless --convert-to pdf:writer_pdf_Export "\tmp\pdfDocument_temp.html" --outdir "\tmp" --norestore --writer`

changing from `soffice` to `sbase.exe` resolved the issue.

Taking the example from the example application

This:

```
string locationOfLibreOfficeSoffice =
                @"F:\PortableApps\LibreOfficePortable\App\libreoffice\program\soffice.exe";
```

becomes:

```
string locationOfLibreOfficeSoffice =
                @"F:\PortableApps\LibreOfficePortable\App\libreoffice\program\sbase.exe";
```

Also, depending on where your applications temporary files are being written to, you may need to update your IIS application pool identity to a specific user account instead of the default. It is also recommended to use `Path.GetTempPath()` for writing temporary files as logged in users do not need any additional permissions to write to this location. Microsoft docs can be found [here](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath?view=net-7.0&tabs=windows) on that method.
